const API=window.API_URL||'http://localhost:3000';const params=new URLSearchParams(location.search);let room=params.get('room')||'sala-'+Math.random().toString(36).slice(2,7);document.querySelector('#roomName').textContent=room;let ws,stream=null,screenStream=null;const video=document.querySelector('#localVideo'),placeholder=document.querySelector('#videoPlaceholder'),messages=document.querySelector('#messages');const user=JSON.parse(localStorage.getItem('cantinho_user')||'{"name":"Visitante"}');
function addMessage(name,text){const d=document.createElement('div');d.className='message';d.innerHTML=`<b>${esc(name)}</b><p>${esc(text)}</p>`;messages.appendChild(d);messages.scrollTop=messages.scrollHeight}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function connect(){try{ws=new WebSocket(API.replace(/^http/,'ws')+'/ws?room='+encodeURIComponent(room)+'&name='+encodeURIComponent(user.name));ws.onopen=()=>ws.send(JSON.stringify({type:'join',name:user.name}));ws.onmessage=e=>{const x=JSON.parse(e.data);if(x.type==='chat')addMessage(x.name,x.text);if(x.type==='count')document.querySelector('#online').textContent=x.count+' online'}}catch(e){}}
async function camera(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null;placeholder.style.display='block';return}try{stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});video.srcObject=stream;placeholder.style.display='none';document.querySelector('#cameraBtn').classList.add('active')}catch(e){alert('Permita o acesso à câmera e ao microfone no navegador.');}}
document.querySelector('#cameraBtn').onclick=camera;
document.querySelector('#micBtn').onclick=()=>{if(!stream)return alert('Ative a câmera primeiro.');const t=stream.getAudioTracks()[0];t.enabled=!t.enabled;document.querySelector('#micBtn').classList.toggle('active',t.enabled)};
document.querySelector('#screenBtn').onclick=async()=>{try{screenStream=await navigator.mediaDevices.getDisplayMedia({video:true});video.srcObject=screenStream;placeholder.style.display='none';screenStream.getVideoTracks()[0].onended=()=>{video.srcObject=stream||null};}catch(e){}};
document.querySelector('#copyBtn').onclick=async()=>{await navigator.clipboard?.writeText(location.href);alert('Link da sala copiado!')};
document.querySelector('#chatForm').onsubmit=e=>{e.preventDefault();const input=document.querySelector('#messageInput'),text=input.value.trim();if(!text)return;if(ws?.readyState===1)ws.send(JSON.stringify({type:'chat',name:user.name,text}));else addMessage(user.name,text);input.value=''};
connect();